package org.mycontrib.ext.customers.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

//------ lombok generation code annotations ------
@Getter @Setter
@ToString(exclude={"address"})
//@EqualsAndHashCode
@NoArgsConstructor
//------------------------------------------------

@Entity
@Table(name="customer")
/*
@NamedQueries({ 
	@NamedQuery(name="findByEmail",query="SELECT c FROM Customer c WHERE c.email=:email")
})*/
public class Customer {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	/* IDENTITY is ok for :
	           H2 (GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)), 
	           MYSQL (auto_increment)
	           POSTGRES (SERIAL or BIG_SERIAL) if not forced .
	   But not for Oracle <= v11 --> META-INF/orm/oracle-orm.xml may be used to override IDENTITY
	*/
	private Long id;
	
	@Column(name="first_name" , length=64)
	private String firstName;
	
	@Column(name="last_name" , length=64)
	private String lastName;
	
	private String email;
	
	@Column(name="phone_number" , length=32)
	private String phoneNumber;
	
	@ManyToOne()
	@JoinColumn(name="address_id")
	private Address address;

	public Customer(Long id, String firstName, String lastName, String email, String phoneNumber) {
		super();
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phoneNumber = phoneNumber;
	}
	
	
	

}
