# .yml (ou .yaml) = syntaxe alternative à .properties
# IMPORTANT = indentation via double espaces mais pas de tabulation !
# localhost:8585/serverRest
server:
  servlet:
    context-path: /serverRest
  port: 8585

#si pb , spring.datasource.url=jdbc:h2:./h2-data/deviseDB

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/deviseDB
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
  data:
    jpa:
      repositories:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8989/realms/myrealm

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/auth/realms/myrealm
#NB: http://localhost:8989_ou_8080/auth/realms/myrealm with keycloak 14
#    http://localhost:8989_ou_8080/realms/myrealm      with keycloack 21

#si elements de liste en .yml .yaml
#liste:
#  - elt: valeur1
#  - elt: valeur2