drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
drop table devise if exists
drop table login if exists
